PARSER_BEGIN(Parser)

package com.yc.parser;

public class Parser {
}

PARSER_END(Parser)

SKIP :
{
    " " | "\t" | "\n" | "\r"
}

TOKEN :
{
    < A01: "cadeia" >
|   < A02: "caracter" >
|   < A03: "declaracoes" >
|   < A04: "enquanto" >
|   < B01: "%" >
|   < B02: "(" >
|   < B03: ")" >
|  < digito: ["0"-"9"] >
}

void Input() :
{}
{
    ( Token() )* <EOF>
}

void Token() :
{}
{
    <A01> | <A02> | <A03> | <A04> | <B01> | <B02> | <B03> | <digito>
}