/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.yc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A01 = 5;
  /** RegularExpression Id. */
  int A02 = 6;
  /** RegularExpression Id. */
  int A03 = 7;
  /** RegularExpression Id. */
  int A04 = 8;
  /** RegularExpression Id. */
  int B01 = 9;
  /** RegularExpression Id. */
  int B02 = 10;
  /** RegularExpression Id. */
  int B03 = 11;
  /** RegularExpression Id. */
  int digito = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"cadeia\"",
    "\"caracter\"",
    "\"declaracoes\"",
    "\"enquanto\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "<digito>",
  };

}
