/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.yc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int A01 = 7;
  /** RegularExpression Id. */
  int A02 = 8;
  /** RegularExpression Id. */
  int A03 = 9;
  /** RegularExpression Id. */
  int A04 = 10;
  /** RegularExpression Id. */
  int A05 = 11;
  /** RegularExpression Id. */
  int A06 = 12;
  /** RegularExpression Id. */
  int A07 = 13;
  /** RegularExpression Id. */
  int A08 = 14;
  /** RegularExpression Id. */
  int A09 = 15;
  /** RegularExpression Id. */
  int A10 = 16;
  /** RegularExpression Id. */
  int A11 = 17;
  /** RegularExpression Id. */
  int A12 = 18;
  /** RegularExpression Id. */
  int A13 = 19;
  /** RegularExpression Id. */
  int A14 = 20;
  /** RegularExpression Id. */
  int A15 = 21;
  /** RegularExpression Id. */
  int A16 = 22;
  /** RegularExpression Id. */
  int A17 = 23;
  /** RegularExpression Id. */
  int A18 = 24;
  /** RegularExpression Id. */
  int A19 = 25;
  /** RegularExpression Id. */
  int A20 = 26;
  /** RegularExpression Id. */
  int A21 = 27;
  /** RegularExpression Id. */
  int A22 = 28;
  /** RegularExpression Id. */
  int A23 = 29;
  /** RegularExpression Id. */
  int A24 = 30;
  /** RegularExpression Id. */
  int A25 = 31;
  /** RegularExpression Id. */
  int A26 = 32;
  /** RegularExpression Id. */
  int B01 = 33;
  /** RegularExpression Id. */
  int B02 = 34;
  /** RegularExpression Id. */
  int B03 = 35;
  /** RegularExpression Id. */
  int B04 = 36;
  /** RegularExpression Id. */
  int B05 = 37;
  /** RegularExpression Id. */
  int B06 = 38;
  /** RegularExpression Id. */
  int B07 = 39;
  /** RegularExpression Id. */
  int B08 = 40;
  /** RegularExpression Id. */
  int B09 = 41;
  /** RegularExpression Id. */
  int B10 = 42;
  /** RegularExpression Id. */
  int B11 = 43;
  /** RegularExpression Id. */
  int B12 = 44;
  /** RegularExpression Id. */
  int B13 = 45;
  /** RegularExpression Id. */
  int B14 = 46;
  /** RegularExpression Id. */
  int B15 = 47;
  /** RegularExpression Id. */
  int B16 = 48;
  /** RegularExpression Id. */
  int B17 = 49;
  /** RegularExpression Id. */
  int B18 = 50;
  /** RegularExpression Id. */
  int B19 = 51;
  /** RegularExpression Id. */
  int B20 = 52;
  /** RegularExpression Id. */
  int B21 = 53;
  /** RegularExpression Id. */
  int B22 = 54;
  /** RegularExpression Id. */
  int C01 = 55;
  /** RegularExpression Id. */
  int C02 = 56;
  /** RegularExpression Id. */
  int C03 = 57;
  /** RegularExpression Id. */
  int C04 = 58;
  /** RegularExpression Id. */
  int C05 = 59;
  /** RegularExpression Id. */
  int C06 = 60;
  /** RegularExpression Id. */
  int C07 = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "<LINE_COMMENT>",
    "\"cadeia\"",
    "\"caracter\"",
    "\"declaracoes\"",
    "\"enquanto\"",
    "\"false\"",
    "\"fimDeclaracoes\"",
    "\"fimEnquanto\"",
    "\"fimFunc\"",
    "\"fimFuncoes\"",
    "\"fimPrograma\"",
    "\"fimSe\"",
    "\"funcoes\"",
    "\"imprime\"",
    "\"inteiro\"",
    "\"logico\"",
    "\"pausa\"",
    "\"programa\"",
    "\"real\"",
    "\"retorna\"",
    "\"se\"",
    "\"senao\"",
    "\"tipoFunc\"",
    "\"tipoParam\"",
    "\"tipoVar\"",
    "\"true\"",
    "\"vazio\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\":=\"",
    "\";\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "<B17>",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "<C01>",
    "<C02>",
    "<C03>",
    "<C04>",
    "<C05>",
    "<C06>",
    "<C07>",
  };

}
